name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 13.126.179.208 
        username: ubuntu 
        key: ${{ secrets.PRIVATE_SSH_KEY }} 
        port: 22
        script: |
          cd ~/ci-cd-with-aws

          # Configure Git to merge safely
          git config pull.rebase false
          git pull origin main

          # Install dependencies (clean install)
          npm ci

          # Build Next.js app
          npm run build

          # Gracefully reload or start with PM2
          pm2 reload next-app || pm2 start npm --name next-app -- start
          pm2 save
